[project]
name = "unified-agent-interface"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "chandralegend", email = "irugalbandarachandra@gmail.com" }
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
unified-agent-interface = "unified_agent_interface:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
